merge master y develop

diff --git a/.github/workflows/pwa-ci-cd.yaml b/.github/workflows/pwa-ci-cd.yaml
--- a/.github/workflows/pwa-ci-cd.yaml
+++ b/.github/workflows/pwa-ci-cd.yaml
@@ -64,24 +64,24 @@ jobs:
       - name: Install Dependencies
         run: npm install
 
-      # 4. Ejecutar pruebas unitarias con Jest y generar reporte de cobertura
-      # - name: Run Unit Tests with Jest
-      #   run: |
-      #     npm test -- --coverage --forceExit --runInBand --bail
-      #     if [ -d coverage ]; then echo "Coverage report generated."; else echo "Coverage report not found!"; exit 1; fi
+      #4. Ejecutar pruebas unitarias con Jest y generar reporte de cobertura
+      - name: Run Unit Tests with Jest
+        run: |
+          npm test -- --coverage --forceExit --runInBand --bail
+          if [ -d coverage ]; then echo "Coverage report generated."; else echo "Coverage report not found!"; exit 1; fi
 
-      # 5. Forzar el final de las pruebas (si queda algún proceso pendiente)
-      # - name: Force End of Tests
-      #   run: |
-      #     echo "Forzando el final de las pruebas"
-      #     exit 0
+      #5. Forzar el final de las pruebas (si queda algún proceso pendiente)
+      - name: Force End of Tests
+        run: |
+          echo "Forzando el final de las pruebas"
+          exit 0
 
-      # 6. Subir el reporte de cobertura como artefacto de GitHub
-      # - name: Upload Coverage Report
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: coverage-report
-      #     path: coverage/
+      #6. Subir el reporte de cobertura como artefacto de GitHub
+      - name: Upload Coverage Report
+        uses: actions/upload-artifact@v3
+        with:
+          name: coverage-report
+          path: coverage/
 
       # 7. Ejecutar pruebas E2E con Cypress
       - name: Run E2E Tests with Cypress
